import bcrypt from 'bcryptjs';

const data  = {
    users : [
        {
            name: 'Biplab',
            email: 'admin@gmail.com',
            password: bcrypt.hashSync('123321'),
            isAdmin: true,

        },
        {
            name: 'Mubin',
            email: 'user@gmail.com',
            password: bcrypt.hashSync('123456'),
            isAdmin: false,

        }
    ],
    products: [
        {
            name: 'Men\'s Linen Light Blue Short Sleeve Shirt',
            slug: 'men\'s linen light blue short sleeve shirt',
            category: 'Shirts',
            image: '/images/shirt1.webp',
            price: 2837,
            brand: 'Nike',
            rating: 8,
            numReviews: 10,
            countInStock: 20,
            description: 'A popular shirt',
        },
        {
            name: 'Men\'s Cotton Red Regular Fit T-shirt',
            slug: 'men\'s cotton red regular fit t-shirt',
            category: 'Shirts',
            image: '/images/shirt2.webp',
            price: 607,
            brand: 'Adidas',
            rating: 4,
            numReviews: 6,
            countInStock: 20,
            description: 'A popular shirt',
        },
        {
            name: 'Men\'s Cotton Grey Melan Fit T-shirt',
            slug: 'men\'s cotton grey melan fit t-shirt',
            category: 'Shirts',
            image: '/images/shirt3.webp',
            price: 854,
            brand: 'Raymond',
            rating: 4.5,
            numReviews: 3,
            countInStock: 20,
            description: 'A popular shirt',
        },
        {
            name: 'Men\'s Cotton Black Regular Fit T-shirt',
            slug: 'men\'s Cotton black regular fit t-shirt',
            category: 'Shirts',
            image: '/images/shirt4.webp',
            price: 853,
            brand: 'Cotton world',
            rating: 6,
            numReviews: 8,
            countInStock: 20,
            description: 'A popular shirt',
        },
        {
            name: 'Women\'s Cotton Rust Regular Fit T-shirt',
            slug: 'women\'s cotton rust regular fit t-shirt',
            category: 'Shirts',
            image: '/images/shirt5.webp',
            price: 793,
            brand: 'Adidas',
            rating: 5,
            numReviews: 10,
            countInStock: 20,
            description: 'A popular shirt',
        },
        {
            name: 'Women\'s Cotton Black Regular Fit T-shirt',
            slug: 'women\'s cotton black regular fit t-shirt',
            category: 'Shirts',
            image: '/images/shirt6.webp',
            price: 793,
            brand: 'Raymond',
            rating: 6,
            numReviews: 11,
            countInStock: 20,
            description: 'A popular shirt',
        },
        {
            name: 'Women\'s Cotton Knit Fit T-shirt',
            slug: 'women\'s cotton knit fit t-shirt',
            category: 'Shirts',
            image: '/images/shirt7.webp',
            price: 793,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 8,
            countInStock: 20,
            description: 'A popular shirt',
        },
        {
            name: 'Women\'s Excel Linen Fit Blouse',
            slug: 'women\'s excel linen fit blouse',
            category: 'Shirts',
            image: '/images/shirt8.webp',
            price: 1108,
            brand: 'Adidas',
            rating: 8,
            numReviews: 10,
            countInStock: 20,
            description: 'A popular shirt',
        },
        {
            name: 'Women\'s Viscose Maroon Fit Jumpsuit',
            slug: 'women\'s viscose maroon fit jumpsuit',
            category: 'Shirts',
            image: '/images/shirt9.webp',
            price: 731,
            brand: 'Raymond',
            rating: 7,
            numReviews: 9,
            countInStock: 20,
            description: 'A popular shirt',
        },
        {
            name: 'Men\'s Cotton Navy Kurta Shirt',
            slug: 'men\'s cotton navy kurta shirt',
            category: 'Shirts',
            image: '/images/shirt10.webp',
            price: 1968,
            brand: 'Casely',
            rating: 8,
            numReviews: 10,
            countInStock: 20,
            description: 'A popular shirt',
        },
        {
            name: 'Men\'s Linen White Kurta Shirt',
            slug: 'men\'s linen white kurta shirt',
            category: 'Shirts',
            image: '/images/shirt11.webp',
            price: 2340,
            brand: 'Nike',
            rating: 8,
            numReviews: 10,
            countInStock: 20,
            description: 'A popular shirt',
        },
        {
            name: 'Men\'s Regular Fit Mandarin Kurta Shirt',
            slug: 'men\'s regular fit mandarin kurta shirt',
            category: 'Shirts',
            image: '/images/shirt12.webp',
            price: 1968,
            brand: 'Raymond',
            rating: 8,
            numReviews: 10,
            countInStock: 20,
            description: 'A popular shirt',
        },
        {
            name: 'Men\'s Cotton White Shirt',
            slug: 'men\'s cotton white shirt',
            category: 'Shirts',
            image: '/images/shirt13.webp',
            price: 2092,
            brand: 'Casely',
            rating: 8,
            numReviews: 10,
            countInStock: 20,
            description: 'A popular shirt',
        },
        {
            name: 'Golf Pants',
            slug: 'golf-pants',
            category: 'Pants',
            image: '/images/pants1.webp',
            price: 2465,
            brand: 'Oliver',
            rating: 2.9,
            numReviews: 13,
            countInStock: 20,
            description: 'Smart looking pants',
        },
        {
            name: 'Fit Pants',
            slug: 'fit-pants',
            category: 'Pants',
            image: '/images/pants2.webp',
            price: 1418,
            brand: 'Zara',
            rating: 3.5,
            numReviews: 7,
            countInStock: 20,
            description: 'A popular pants',
        },
        {
            name: 'Classic Pants',
            slug: 'classic-pants',
            category: 'Pants',
            image: '/images/pants3.webp',
            price: 1226,
            brand: 'Casely',
            rating: 2.4,
            numReviews: 14,
            countInStock: 20,
            description: 'A popular pants',
        },

    ]
}

export default data;